<?php
/**
 * @var \DCFramework\Template $this
 */
?>
<div class="dcDebug">

    <?php if(count(\DCFramework\Storage::$errors)>0):
        ?>
        <div class="dcDebugErrors">
            <?php foreach(\DCFramework\Storage::$errors as $error): ?>
                <p>
                    <span><b>Error:</b> <?=$error['message']?></span><br/>
                    <em>File: <?=$error['file']?> (<?=$error['line']?>)</em>
                </p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

</div>
